web_android/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.dashboard.index');
});
	Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/menu', 'Admin\Menu\MenuController');
    Route::resource('/satuan', 'Admin\Satuan\SatuanController');
    Route::resource('/kategori', 'Admin\Kategori\KategoriController');

web_android/app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    protected $table = 'kategori';
    protected $fillable = ['id_kategori','nama_kategori'];
    protected $primaryKey = 'id_kategori';
}

web_android/app/Http/Controllers/Admin/Kategori/KategoriController.php
<?php

namespace App\Http\Controllers\Admin\Kategori;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Kategori;


class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = Kategori::all();
        return view('admin.kategori.index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.kategori.create');    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $kategori = new Kategori();

        $kategori->id_kategori = $request->input('id_kategori');
        $kategori->nama_kategori = $request->input('nama_kategori');
        $kategori->timestamps = false;
        $kategori->save();

        \Session::flash('sukses','Data Berhasil Ditambahkan');
        return redirect('/kategori');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id_kategori)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id_kategori)
    {
        $kategori = Kategori::findorfail($id_kategori);
        return view('admin.kategori.edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_kategori)
    {
        $kategori = Kategori::findorfail($id_kategori);

        $kategori->id_kategori = $request->input('id_kategori');
        $kategori->nama_kategori = $request->input('nama_kategori');
        $kategori->timestamps = false;
        $kategori->save();

        \Session::flash('sukses','Data Berhasil Diupdate');
        return redirect('/kategori');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_kategori)
    {
        $kategori = Kategori::findorfail($id_kategori);
        $kategori->delete();

        \Session::flash('sukses','Data Berhasil Dihapus');
        return redirect('/kategori');
    }
}

web_android/resources/views/admin/kategori/create.blade.php
@extends('layouts.master')
@section('sub-judul','Tambah Kategori')
@section('jejak','Tambah Kategori')
@section('content')

<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
            		<thead>
                		<form action="{{ route('kategori.store') }}" method="POST">
                		@csrf
                		<thead>
                		<div class="form-group">
                        <label >Id Kategori</label>
                        <input name="id_kategori" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Id Kategori" value="">
                    </div>
                    <div class="form-group">
                    		<label >Nama Kategori</label>
                    		<input name="nama_kategori" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Nama Kategori" value="">
               			 </div>
                    		<button type="submit" class="btn btn-success">Tambah</button>
            			</form>
            		</thead>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection

web_android/resources/views/admin/kategori/edit.blade.php
@extends('layouts.master')
@section('sub-judul','Edit Kategori')
@section('jejak','Edit Kategori')
@section('content')

<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">             
                <div class="row">
                    <div class="col-sm-12">
                <thead>
                    <form action="{{ route('kategori.update', $kategori->id_kategori ) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('patch')
                    <thead>
                    <div class="form-group">
                        <label >Id Kategori</label>
                        <input name="id_kategori" type="text" value="{{ $kategori->id_kategori }}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Id Kategori" value="">
                    </div>
                    <div class="form-group">
                        <label >Nama Kategori</label>
                        <input name="nama_kategori" type="text" value="{{ $kategori->nama_kategori }}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Nama Kategori" value="">
                     </div>
                        <button type="submit" class="btn btn-success">Update</button>
                  </form>
                </thead>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection

web_android/resources/views/admin/kategori/index.blade.php
@extends('layouts.master')
@section('sub-judul','Kategori')
@section('jejak','Kategori')
@section('content')

<!-- Main content -->
    <section class="content">
      <div class="row">
          <div class="col-12">
        <!-- SELECT2 EXAMPLE -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Data Kategori</h3>
            <div class="text-right">
                <a href="{{ route('kategori.create') }}" class="btn btn-success btn-sm float-leftt">
                    <i class="fas fa-plus"></i>
                </a>
            </div>
          </div>
            <!-- /.card-header -->
            <div class="card-body">
              <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                  <div class="row"><div class="col-sm-12 col-md-6">
                        <div class="dataTables_length" id="example1_length">
                            
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">

                <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                <thead>
                <tr>
                    <th>Id Kategori</th>
                    <th>Nama Kategori</th>
                    <th>Opsi</th>
                </tr>
            </thead>
                <tbody>
                @php $no = 1; 
                @endphp
                @foreach ($kategori as $result => $hasil)
                <tr>
                    <td>{{ $hasil->id_kategori}}</td>
                    <td>{{ $hasil->nama_kategori}}</td>
                    <td>
                      <form action="{{ route('kategori.destroy', $hasil->id_kategori) }}" method="POST">
                        @csrf
                        @method('delete')
                        <a href="{{ route('kategori.edit', $hasil->id_kategori ) }}" class="btn btn-info btn-sm">
                          <i class="fas fa-edit"></i>
                        </a>
                        <button type="submit" class="btn btn-danger btn-sm" onClick="return confirm('Yakin Mau Dihapus')">
                          <i class="fas fa-trash"></i>
                        </button>
                      </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
            </table>
            </div>
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection