web_android/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.dashboard.index');
});
	Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/menu', 'Admin\Menu\MenuController');
    Route::resource('/satuan', 'Admin\Satuan\SatuanController');
    Route::resource('/kategori', 'Admin\Kategori\KategoriController');

web_android/app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    protected $table = 'menu';
    protected $fillable = ['id_menu','nama','id_satuan','id_kategori','harga','photos'];
    protected $primaryKey = 'id_menu';
    
    public function satuan()
    {
        return $this->belongsTo('App\Models\Satuan','id_satuan');
    }
    
    public function kategori()
    {
        return $this->belongsTo('App\Models\Kategori','id_kategori');
    }
}

web_android/app/Http/Controllers/Admin/Menu/MenuController.php
<?php

namespace App\Http\Controllers\Admin\Menu;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Menu;
use App\Models\Satuan;
use App\Models\Kategori;


class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menu = Menu::all();
        return view('admin.menu.index', compact('menu'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $satuan = Satuan::all();
        $kategori = Kategori::all();
        return view('admin.menu.create', compact('satuan','kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $menu = new Menu();

        $menu->id_menu = $request->input('id_menu');
        $menu->nama = $request->input('nama');
        $menu->id_kategori = $request->input('id_kategori');
        $menu->id_satuan = $request->input('id_satuan');
        $menu->harga = $request->input('harga');

            if ($request->hasfile('photos')) {
                $file = $request->file('photos');
                $extension = $file->getClientOriginalExtension();
                $filename = 'DC'.date('YmdHis') . '.' . $extension;
                $file->move('images/', $filename);
                $menu->photos = $filename;
            } else{
                return $request;
                $menu->photos = '';
            }
            $menu->timestamps = false;
            $menu->save();


        \Session::flash('sukses','Data Berhasil Ditambahkan');  
        return redirect('/menu');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id_menu
     * @return \Illuminate\Http\Response
     */
    public function show($id_menu)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id_menu
     * @return \Illuminate\Http\Response
     */
    public function edit($id_menu)
    {
        $satuan = Satuan::all();
        $kategori = Kategori::all();
        $menu = Menu::findorfail($id_menu);
        return view('admin.menu.edit', compact('menu','satuan', 'kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id_menu
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_menu)
    {
        $menu = Menu::findorfail($id_menu);

        $menu->id_menu = $request->input('id_menu');
        $menu->nama = $request->input('nama');
        $menu->id_kategori = $request->input('id_kategori');
        $menu->id_satuan = $request->input('id_satuan');
        $menu->harga = $request->input('harga');

            if ($request->hasfile('photos')) {
                $file = $request->file('photos');
                $extension = $file->getClientOriginalExtension();
                $filename = 'DC'.date('YmdHis') . '.' . $extension;
                $file->move('images/', $filename);
                $menu->photos = $filename;
            }
            $menu->timestamps = false;
            $menu->save();


        \Session::flash('sukses','Data Berhasil Diupdate');  
        return redirect('/menu');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id_menu
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_menu)
    {
        $menu = Menu::findorfail($id_menu);
        $menu->delete();

        \Session::flash('sukses','Data Berhasil Dihapus');
        return redirect('/menu');
    }
}

web_android/resources/views/admin/menu/create.blade.php
@extends('layouts.master')
@section('sub-judul','Tambah Menu')
@section('jejak','Tambah Menu')
@section('content')

<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
            		<thead>
                		<form action="{{ route('menu.store') }}" method="POST" enctype="multipart/form-data">
                		@csrf
                		<thead>
                		<div class="form-group">
                    		<label >Id Menu</label>
                    		<input name="id_menu" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Id Menu" value="">
               			 </div>
                     <div class="form-group">
                        <label >Nama Menu</label>
                        <input name="nama" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Nama Menu" value="">
                     </div>
               			 <div class="form-group">
                    		<label>Satuan</label>
                    		<select class="form-control" name="id_satuan">
                    			<option value="" holder>Pilih Satuan</option>
                    			@foreach($satuan as $result)
                    			<option value="{{ $result['id_satuan']}}">{{ $result->nama_satuan }}</option>
                    			@endforeach
                    		</select>
               			 </div>
               			 <div class="form-group">
                    		<label >Kategori</label>
                    		<select class="form-control" name="id_kategori">
                    			<option value="" holder>Pilih Kategori</option>
                    			@foreach($kategori as $result)
                    			<option value="{{ $result['id_kategori']}}">{{ $result->nama_kategori}}</option>
                    			@endforeach
                    		</select>
               			 </div>
                     <div class="form-group">
                        <label >Harga</label>
                        <input name="harga" type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Harga" value="">
                     </div>
                     <div class="form-group">
                        <label >Foto</label>
                        <input name="photos" type="file" class="form-control">
                     </div>
                    		<button type="submit" class="btn btn-success">Tambah</button>
            			</form>
            		</thead>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection

web_android/resources/views/admin/menu/edit.blade.php
@extends('layouts.master')
@section('sub-judul','Edit Menu')
@section('jejak','Edit Menu')
@section('content')

<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                <thead>
                    <form action="{{ route('menu.update', $menu->id_menu ) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('patch')
                    <thead>
                      <div class="form-group">
                        <label >Id Menu</label>
                        <input name="id_menu" type="text" value="{{ $menu->id_menu }}" class="form-control">
                     </div>
                    <div class="form-group">
                        <label >Nama Menu</label>
                        <input name="nama" type="text" value="{{ $menu->nama }}" class="form-control">
                     </div>
                     <div class="form-group">
                    		<label >Satuan</label>
                    		<select class="form-control" name="id_satuan">
                    			<option holder>Pilih Satuan</option>
                    			@foreach($satuan as $result)
                    			<option value="{{ $result['id_satuan']}}" 
                    			@if($menu->id_satuan == $result->id_satuan)
                    				selected
                    			@endif>{{ $result->nama_satuan }}</option>
                    			@endforeach
                    		</select>
               			 </div>
               			 <div class="form-group">
                    		<label >Kategori</label>
                    		<select class="form-control" name="id_kategori">
                    			<option holder>Pilih Kategori</option>
                    			@foreach($kategori as $result)
                    			<option value="{{ $result['id_kategori']}}"
                    			@if($menu->id_kategori == $result->id_kategori)
                    				selected
                    			@endif
                    			>{{ $result->nama_kategori}}</option>

                    			@endforeach
                    		</select>
               			 </div>
                     <div class="form-group">
                        <label >Harga</label>
                        <input name="harga" type="number" value="{{ $menu->harga }}" class="form-control">
                     </div>
                     <div class="form-group">
                        <label >Foto</label>
                        <input name="photos" type="file" value="{{ $menu->photos }}" class="form-control">
                     </div>
                        <button type="submit" class="btn btn-success">Update</button>
                  </form>
                </thead>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection

web_android/resources/views/admin/menu/index.blade.php
@extends('layouts.master')
@section('sub-judul','Menu')
@section('jejak','Menu')
@section('content')

<!-- Main content -->
    <section class="content">
        <div class="row">
          <div class="col-12">
        <!-- SELECT2 EXAMPLE -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Data Menu</h3>
            <div class="text-right">
                <a href="{{ route('menu.create') }}" class="btn btn-success btn-sm float-leftt">
                    <i class="fas fa-plus"></i>
                </a>
            </div>
          </div>
            <!-- /.card-header -->
            <div class="card-body">
              <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                  <div class="row"><div class="col-sm-12 col-md-6">
                        <div class="dataTables_length" id="example1_length">
                            
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">

                <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                <thead>
                <tr>
                    <th>Id Menu</th>
                    <th>Nama Menu</th>
                    <th>Kategori</th>
                    <th>Satuan</th>
                    <th>Harga</th>
                    <th>Foto</th>
                    <th>Opsi</th>
                </tr>
            </thead>
                <tbody>
                @php 
                $no = 1; 
                @endphp
                @foreach ($menu as $result => $hasil)
                <tr>
                    <td>{{ $hasil->id_menu }}</td>
                    <td>{{ $hasil->nama}}</td>
                    <td>{{ $hasil->kategori->nama_kategori}}</td>
                    <td>{{ $hasil->satuan->nama_satuan}}</td>
                    <td>Rp. {{number_format($hasil->harga)}}</td>
                    <td><img src="images/<?php echo $hasil['photos']; ?>" style="width: 100px;"></td>
                    <td>
                      <form action="{{ route('menu.destroy', $hasil->id_menu) }}" method="POST">
                        @csrf
                        @method('delete')
                        <a href="{{ route('menu.edit', $hasil->id_menu) }}" class="btn btn-info btn-sm">
                          <i class="fas fa-edit"></i>
                        </a>
                        <button type="submit" class="btn btn-danger btn-sm" onClick="return confirm('Yakin Mau Dihapus')">
                          <i class="fas fa-trash"></i>
                        </button>
                      </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
            </table>
            </div>
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection