web_android/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.dashboard.index');
});
	Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/menu', 'Admin\Menu\MenuController');
    Route::resource('/satuan', 'Admin\Satuan\SatuanController');
    Route::resource('/kategori', 'Admin\Kategori\KategoriController');

web_android/app/Models/Satuan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Satuan extends Model
{
    protected $table = 'satuan';
    protected $fillable = ['id_satuan','nama_satuan'];
    protected $primaryKey = 'id_satuan';
}

web_android/app/Http/Controllers/Admin/Satuan/SatuanController.php
<?php

namespace App\Http\Controllers\Admin\Satuan;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Satuan;


class SatuanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $satuan = Satuan::all();
        return view('admin.satuan.index', compact('satuan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.satuan.create');    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $satuan = new Satuan();

        $satuan->id_satuan = $request->input('id_satuan');
        $satuan->nama_satuan = $request->input('nama_satuan');
        $satuan->timestamps = false;
        $satuan->save();

        \Session::flash('sukses','Data Berhasil Ditambahkan');
        return redirect('/satuan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id_satuan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id_satuan)
    {
        $satuan = Satuan::findorfail($id_satuan);
        return view('admin.satuan.edit', compact('satuan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_satuan)
    {
        $satuan = Satuan::findorfail($id_satuan);

        $satuan->id_satuan = $request->input('id_satuan');
        $satuan->nama_satuan = $request->input('nama_satuan');
        $satuan->timestamps = false;
        $satuan->save();

        \Session::flash('sukses','Data Berhasil Diupdate');
        return redirect('/satuan');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_satuan)
    {
        $satuan = Satuan::findorfail($id_satuan);
        $satuan->delete();

        \Session::flash('sukses','Data Berhasil Dihapus');
        return redirect('/satuan');
    }
}

web_android/resources/views/admin/satuan/create.blade.php
@extends('layouts.master')
@section('sub-judul','Tambah Satuan')
@section('jejak','Tambah Satuan')
@section('content')

<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
            		<thead>
                		<form action="{{ route('satuan.store') }}" method="POST">
                		@csrf
                		<thead>
                		<div class="form-group">
                        <label >Id Satuan</label>
                        <input name="id_satuan" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Id Satuan" value="">
                    </div>
                    <div class="form-group">
                    		<label >Nama Satuan</label>
                    		<input name="nama_satuan" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Nama Satuan" value="">
               			 </div>
                    		<button type="submit" class="btn btn-success">Tambah</button>
            			</form>
            		</thead>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection

web_android/resources/views/admin/satuan/edit.blade.php
@extends('layouts.master')
@section('sub-judul','Edit Satuan')
@section('jejak','Edit Satuan')
@section('content')

<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                <thead>
                    <form action="{{ route('satuan.update', $satuan->id_satuan ) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('patch')
                    <thead>
                    <div class="form-group">
                        <label >Id Satuan</label>
                        <input name="id_satuan" type="text" value="{{ $satuan->id_satuan }}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Id Satuan" value="">
                    </div>
                    <div class="form-group">
                        <label >Nama Satuan</label>
                        <input name="nama_satuan" type="text" value="{{ $satuan->nama_satuan }}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Nama Satuan" value="">
                     </div>
                        <button type="submit" class="btn btn-success">Update</button>
                  </form>
                </thead>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection

web_android/resources/views/admin/satuan/index.blade.php
@extends('layouts.master')
@section('sub-judul','Satuan')
@section('jejak','Satuan')
@section('content')

<!-- Main content -->
    <section class="content">
      <div class="row">
          <div class="col-12">
        <!-- SELECT2 EXAMPLE -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Data Satuan</h3>
            <div class="text-right">
                <a href="{{ route('satuan.create') }}" class="btn btn-success btn-sm float-leftt">
                    <i class="fas fa-plus"></i>
                </a>
            </div>
          </div>
            <!-- /.card-header -->
            <div class="card-body">
              <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                  <div class="row"><div class="col-sm-12 col-md-6">
                        <div class="dataTables_length" id="example1_length">
                            
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">

                <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                <thead>
                <tr>
                  <th>Id Satuan</th>
                  <th>Nama Satuan</th>
                  <th>Opsi</th>
                </tr>
            </thead>
                <tbody>
                @php $no = 1; 
                @endphp
                @foreach ($satuan as $result => $hasil)
                <tr>
                    <td>{{ $hasil->id_satuan}}</td>
                    <td>{{ $hasil->nama_satuan}}</td>
                    <td>
                      <form action="{{ route('satuan.destroy', $hasil->id_satuan) }}" method="POST">
                        @csrf
                        @method('delete')
                        <a href="{{ route('satuan.edit', $hasil->id_satuan) }}" class="btn btn-info btn-sm">
                          <i class="fas fa-edit"></i>
                        </a>
                        <button type="submit" class="btn btn-danger btn-sm" onClick="return confirm('Yakin Mau Dihapus')">
                          <i class="fas fa-trash"></i>
                        </button>
                      </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
            </table>
            </div>
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection